Добавляет наставника
htmlacademy-htmlcss/2249653-sedona-36 pull request #1
Opened 2023-01-17 17:37 UTC by valery163

2023-01-17 19:07 UTC, pavel-nyukalo requested changes

2023-01-17 19:07 UTC, pavel-niukalo commented on Readme.md
> +* Наставник: `Павел Нюкало`(https://htmlacademy.ru/profile/nyukalopavel).
Это у нас синтаксис `markdown`, и поэтому важно соблюдать его правила. Для ссылок это - `[Текст](сама ссылка)`. Иначе ссылка выглядит вот так

![image](https://user-images.githubusercontent.com/52506235/212983173-6d25b8ef-4219-4ebc-bbd5-7e61178ef0b2.png)

2023-01-18 13:13 UTC, valery163 commented on Readme.md
> +* Наставник: `Павел Нюкало`(https://htmlacademy.ru/profile/nyukalopavel).
Я все исправила, новый коммит есть)

2023-01-19 05:52 UTC, pavel-nyukalo approved these changes

2023-01-19 05:52 UTC, merged