Создает разметку на главной странице и в каталоге
htmlacademy-htmlcss/2249653-sedona-36 pull request #2
Opened 2023-01-23 05:21 UTC by valery163

Привет, в моем коде подсвечены зеленой полосой вопросы которые обсуждались в общем чате твоих студентов в дискорде:
1. Как зафиксировать сколько найдено гостиниц. (на макете: Найдено гостиниц; 38).
2. Добавить звезды рейтинга. 

Не смогла разобраться в чем моя ошибка(

2023-01-23 15:05 UTC, pavel-nyukalo requested changes

2023-01-23 15:05 UTC, pavel-niukalo commented on index.html
> +            </span>
По критериям скрытому описанию нужно добавлять точку в конце. Относится ко всем таким элементам

![image](https://user-images.githubusercontent.com/52506235/214066084-225af47c-c6e7-4d72-b98f-b579d68cd484.png)

2023-01-23 15:05 UTC, pavel-niukalo commented on index.html
> +        </ul>
Тут я думаю список излишен, просто два параграфа

2023-01-23 15:05 UTC, pavel-niukalo commented on index.html
> +              <p class="advantages-description">Седона — не аттракцион для туристов, там течёт своя жизнь</p>
Немного форматирование поехало. Двумя пробелами должны отделяться вложенные теги, а `p` у нас не вложен в `h3` (и не должен)

То бишь должно быть так
```html
<h3></h3>
<p></p>
```

2023-01-23 15:05 UTC, pavel-niukalo commented on index.html
> +          </li>
Так же в этот `li` нужно положить картинку, ибо они контентная

2023-01-23 15:05 UTC, pavel-niukalo commented on index.html
> +          </li>
Тут тоже картинку нужно добавить

2023-01-23 15:05 UTC, pavel-niukalo commented on index.html
> +        </ul>
Тут так же думаю список излишен, можно просто двумя параграфами

2023-01-23 15:05 UTC, pavel-niukalo commented on index.html
> +              <p class="sentence-description">Рекомендуем пожить в настоящем мотеле, всё как в кино!</p>
+1 про отступы

2023-01-23 15:05 UTC, pavel-niukalo commented on index.html
> +        </ul>
+1 про излишество списка

2023-01-23 15:05 UTC, pavel-niukalo commented on index.html
> +      <section class="'subscribe">
Лишняя `'` в названии класса

Плюс я думаю, секцию с подпиской можно в футер положить, она на обоих страницах встречается

![image](https://user-images.githubusercontent.com/52506235/214070547-f7ceb12c-141f-4753-8b21-e24ec0c1f8fc.png)

2023-01-23 15:05 UTC, pavel-niukalo commented on catalog.html
> +              </label>
Для лучшей читабельности предложил бы подпись перенести на новую строку

```html
<label class="control">
  <input class="control-input" type="checkbox" name="Swimming-pool" checked>
  Бассейн
</label>
```

2023-01-23 15:05 UTC, pavel-niukalo commented on catalog.html
> +         </ul>
Тут вот тоже немного отступы поехали, между закрывающим `li` и закрывающим `ul`

Можешь в VSCode нажать Ctrl + Shift + P -> format document..

2023-01-23 15:05 UTC, pavel-nyukalo commented on catalog.html
> +        <fieldset class="inner-header-filter-group">
Это у нас форма, поэтому нужно обернуть в `form`

![image](https://user-images.githubusercontent.com/52506235/214072022-58cfe2c8-a3b5-4b4d-a175-05c5c19369f6.png)

2023-01-23 15:05 UTC, pavel-nyukalo commented on catalog.html
> +        </ul>
И после того как обернешь в форму, это можно будет сделать кнопками, с типами `submit` и `reset`. Они как раз для этого. И список тут тоже не нужен

2023-01-23 15:05 UTC, pavel-nyukalo commented on catalog.html
> +          </li>
+1 про лишний список

2023-01-23 15:05 UTC, pavel-nyukalo commented on catalog.html
> +      </a>
А вот здесь как раз можно список сделать

2023-01-23 15:05 UTC, pavel-nyukalo commented on catalog.html
> +          </a>
"Гостиница" уже не относится к ссылке, поэтому лучше вынести

2023-01-23 15:05 UTC, pavel-nyukalo commented on catalog.html
> +          <a class="product-card-button-rating button" href="#">Рейтинг</a>
Звезды и Рейтинг на ссылки не похожи, поэтому можно просто тегами

2023-01-23 15:05 UTC, pavel-nyukalo commented on catalog.html
> +    </section>
![image](https://user-images.githubusercontent.com/52506235/214073560-edf77047-9c9f-48f9-9540-7eb8f0cead0a.png)

2023-01-24 13:59 UTC, valery163 commented on index.html
> +            </span>
Исправила

2023-01-24 13:59 UTC, valery163 commented on index.html
> +        </ul>
Заменила на два параграфа

2023-01-24 13:59 UTC, valery163 commented on index.html
> +              <p class="advantages-description">Седона — не аттракцион для туристов, там течёт своя жизнь</p>
Не усмотрела( Исправила

2023-01-24 14:05 UTC, valery163 commented on index.html
> +          </li>
Добавила, прям совсем не уверена, что правильно, хотела бы обсудить на консультации этот вопрос.

2023-01-24 14:05 UTC, valery163 commented on index.html
> +          </li>
Тоже добавила, но не уверена в правильности

2023-01-24 14:12 UTC, valery163 commented on index.html
> +        </ul>
Т.е. получается, что параграфы заключены в  секцию? Правильно? Сделала именно так, нужно понять почему. Предлагаю этот вопрос тоже понять на консультации.

2023-01-24 14:13 UTC, valery163 commented on index.html
> +              <p class="sentence-description">Рекомендуем пожить в настоящем мотеле, всё как в кино!</p>
Исправила, похоже нужно перечитать еще раз про вложенные элементы. Ошибки одинаковые.

2023-01-24 14:19 UTC, valery163 commented on index.html
> +        </ul>
Исправила, но тоже предлагаю тоже разобрать на консультации случае, когда какие теги выбирать для списков и для параграфов

2023-01-24 14:24 UTC, valery163 commented on index.html
> +      <section class="'subscribe">
1.Надо быть внимательнее(
2.При выполнении задания сомневалась, в том что эту секцию нужно оставить в основном разделе...

2023-01-24 14:28 UTC, valery163 commented on catalog.html
> +              </label>
Исправила.
Но только вот остался вопрос это касается всех подписей или только этих. Тоже обсудила бы на консультации.

2023-01-24 14:40 UTC, valery163 commented on catalog.html
> +         </ul>
Формат документа срабатывает на основе настроек VSCode или применяется плагин .editorconfig или они не противоречат друг другу?

2023-01-24 15:13 UTC, valery163 commented on catalog.html
> +        <fieldset class="inner-header-filter-group">
Исправила, а форму то тут я и не признала(((

2023-01-24 15:15 UTC, valery163 commented on catalog.html
> +        </ul>
Тоже исправила... не разобралась с формой совсем. Надо к ней еще раз вернуться.

2023-01-24 15:17 UTC, valery163 commented on catalog.html
> +          </li>
Это уже диагноз - "листянка".

2023-01-24 15:48 UTC, valery163 commented on catalog.html
> +      </a>
Исправила, хочется разобраться: Почему так? В примере Барбершопа не было списков. Понимаю, что написание кода это творческий процесс, но все же есть свои правила и хочется их постичь.

2023-01-24 16:38 UTC, valery163 commented on catalog.html
> +          </a>
Вынесла из списка

2023-01-24 16:40 UTC, valery163 commented on catalog.html
> +          <a class="product-card-button-rating button" href="#">Рейтинг</a>
Просто теги это значит <p>?

2023-01-24 16:40 UTC, valery163 commented on catalog.html
> +          <a class="product-card-button-rating button" href="#">Рейтинг</a>
тег р не пропечатался(

2023-01-24 16:41 UTC, valery163 commented on catalog.html
> +    </section>
Через валидатор ошибок нет, только предупреждения.

2023-01-25 07:46 UTC, pavel-nyukalo requested changes

2023-01-25 07:46 UTC, pavel-nyukalo commented on index.html
> +          <li class="advantages-item"><img src="#" alt="Городок Седона" class="rightimg">
Единственное, давай ее перенесем на новую строку, для удобочитаемости

И наверное лучше в конец картинку сунуть, чтобы потом стилизовать было легче

После сеток у нас вообще скорее всего будет так

![image](https://user-images.githubusercontent.com/52506235/214500392-d9e3ca7f-d75e-4541-9257-12fc91965722.png)

То бишь

```html
<li>
  <div>
    <h3>
    <p>
  </div>
  
  <img>
</li>
```

Но пока можно без дива, просто картинку в конец положить

2023-01-25 07:46 UTC, pavel-nyukalo commented on index.html
> +            <p class="advantages-description">Да, по нему можно пройти! Если вы осмелитесь, разумеется</p>
Аналогично, но опять же потом, для лучшей стилизации - здесь картинку можно уже перед текстом, то есть в начале

2023-01-25 07:46 UTC, pavel-nyukalo commented on index.html
> +        <p class="service-description">Приезжайте в Седону отдохнуть в комфорте и уюте!</p>
Заголовок не нужно удалять, пусть будет. Плюс по критериям у нас у секций должны быть заголовки

![image](https://user-images.githubusercontent.com/52506235/214500143-8a21fc96-d736-4ceb-b4e4-529baa32b96d.png)

Либо "Приезжайте в Седону отдохнуть в комфорте и уюте!" сделать заголовком

2023-01-25 07:46 UTC, pavel-nyukalo commented on index.html
> +        <p class="interest-description">Заинтересовались?</p>
Аналогично про заголовок

2023-01-25 07:46 UTC, pavel-nyukalo commented on catalog.html
> +          <form class="filter-group" action="https://echo.htmlacademy.ru/" method="post">
Формой у нас является весь блок на скриншоте

![image](https://user-images.githubusercontent.com/52506235/214506088-08e64c60-b1e1-4260-bc7b-1b9e6d8bc897.png)

И еще `fieldset class="inner-header-filter-group"` должен быть в этой форме.

То есть по итогу должно получиться так

```html
<form class="filter-group" action="https://echo.htmlacademy.ru/" method="post">
  <fieldset class="inner-header-filter-group">
    <legend class="inner-header-filter-group">Инфраструктура</legend>
    ...
  </fieldset>
  
  <fieldset class="inner-header-filter-group">
    <legend class="inner-header-filter-group">Тип жилья</legend>
    ...
  </fieldset>
  
  Тут потом еще будет с целой блок
  
  <button class="button" type="submit">Применить</button>
  <button class="button" type="submit">Сбросить</button>
</form>
```

2023-01-25 07:46 UTC, pavel-nyukalo commented on catalog.html
> +          <input type="text">
Вот эти инпуты не очень понял зачем нужно. Это блок с ценой в будущем?

2023-01-25 07:46 UTC, pavel-nyukalo commented on catalog.html
> +          <button class="button" type="submit">Сбросить</button>
У "сбросить" в HTML есть свой type - `reset`, нужно его указать

2023-01-25 07:46 UTC, pavel-nyukalo commented on catalog.html
> +          <p class="search-results-description">38</p>
"Найдено гостиниц" два раза указано, опечатка или так и задумывалось?

2023-01-25 07:46 UTC, pavel-nyukalo commented on catalog.html
> +          <li class="product-card">
Тут валидационная ошибка - в тег `ul` можно вкладывать _только_ теги `li`. То есть все остальное должно быть внутри `li`.

Поэтому 
```html
<p class="product-card-type">Гостиница</p>
<p class="product-card-type visually-hidden">Звезды</p>
```

нужно удалить

2023-01-25 07:46 UTC, pavel-nyukalo commented on catalog.html
> +            <a class="product-card-button-rating button" href="#">Рейтинг</a>
Как уже писал, тут ссылки не нужны. Да, это просто `p` у нас будет, или `span`. Почему не пропечатался? Может сохранить файл забыла? На консультации разберем

2023-01-25 15:28 UTC, valery163 commented on index.html
> +          <li class="advantages-item"><img src="#" alt="Городок Седона" class="rightimg">
Исправила без дивов.

2023-01-25 15:30 UTC, valery163 commented on index.html
> +        <p class="service-description">Приезжайте в Седону отдохнуть в комфорте и уюте!</p>
Сделал заголовком Приезжайте в Седону отдохнуть в комфорте и уюте!

2023-01-25 16:14 UTC, valery163 commented on catalog.html
> +          <form class="filter-group" action="https://echo.htmlacademy.ru/" method="post">
Недостающее внесла в форму. Блок добавила, но только не поняла как саму стоимость добавить в ячейки т.е. о и 9000

2023-01-25 16:14 UTC, valery163 commented on catalog.html
> +          <input type="text">
Инпуты убрала, они тут не нужны, конечно.

2023-01-25 16:19 UTC, valery163 commented on catalog.html
> +          <button class="button" type="submit">Сбросить</button>
Т.е. могут быть два type? Наверно так не правильно(

2023-01-29 15:44 UTC, pavel-nyukalo approved these changes

2023-01-29 15:44 UTC, merged