Исправляю html после замечаний на консультации и начинаю создавать css
htmlacademy-htmlcss/2249653-sedona-36 pull request #3
Opened 2023-02-06 14:57 UTC by valery163

Исправляю html после замечаний на консультации и начинаю создавать css

2023-02-10 09:30 UTC, pavel-nyukalo requested changes

2023-02-10 09:30 UTC, pavel-nyukalo commented on catalog.html
> +            </a>
Здесь у нас должно быть три ссылки - картинка с заголовком, подробнее и избранное. Сейчас получается что это все одна ссылка, которая будет вести в одно место

Должно получить так

```html
<li class="product-card">
  <article class="product-card">
    <a class="product-card-link" href="product.html">
      <img class="product-card-image" src="images/catalog-main-images/card-villas-at-poco.jpg" width="300"
      height="212" alt="Госница Villas at Poco Diablo.">
      <h3 class="product-card-title">Villas at Poco Diablo</h3>
    </a>
    <a href="#" class="product-card-detail">Подробнее</a>
    <a href="#" class="product-card-favorites">Избранное</a>
    <p class="product-card-type">Гостиница</p>
    <b class="product-card-price">От 5000 ₽</b>
    <p class="product-card-rating">Рейтинг</p>
  </article>
</li>
```

2023-02-10 09:30 UTC, pavel-nyukalo commented on catalog.html
> +        </article>
Неправильно закрыты теги, `article` вложен в `li`, в нем и должен быть закрыт

2023-02-10 09:30 UTC, pavel-nyukalo commented on catalog.html
> +        </article>
+1

2023-02-10 09:30 UTC, pavel-nyukalo commented on catalog.html
> +            </a>
Про ссылки относится ко всем карточкам

2023-02-10 09:30 UTC, pavel-nyukalo commented on index.html
> +            </a>
В каталоге тоже нужно так же сделать

2023-02-10 09:30 UTC, pavel-nyukalo commented on index.html
> +            </a>
1. Так же нужно и в каталоге сделать
2. У "12" можно точку не делать. Этот текст не подпись к элементу, плюс по макету не попадем

2023-02-10 09:30 UTC, pavel-nyukalo commented on index.html
> -      </section>
Разметку нам нужно оставить. На консультации мы проговаривали про картинки - вот их да удаляем (будем делать фоном). А сам список в разметке оставить нужно конечно

2023-02-10 09:30 UTC, pavel-nyukalo commented on index.html
> -        <form class="subscribe-form" action="https://echo.htmlacademy.ru/" method="post">
`<form>` тоже нужно оставить

2023-02-10 09:30 UTC, pavel-nyukalo commented on index.html
> +            </svg>
Уже хорошо, но еще нужно добавить отступ у `<path>`. Он уже вложенный для `<svg>`

2023-02-10 09:30 UTC, pavel-nyukalo commented on index.html
> +            </svg>
Плюс так же в каталог не забудь добавить эту реализацию

Хедер и футер у нас почти одинаковые на двух страницах, поэтому если на одной странице такая реализация - то и на второй она же должна быть

2023-02-10 09:30 UTC, pavel-nyukalo commented on styles/styles.css
> +  src: url("..\fonts\ptsans-400.woff2") format("woff2");
`\` лучше заменить на `/` - поскольку `\` может вызвать проблемы на разных ОС

2023-02-10 09:30 UTC, pavel-nyukalo commented on styles/styles.css
> +  }
У второго `font-face` нет закрывающего `}`

Плюс отступы у `body` и его свойств больше чем нужно

Должно быть 

```css
@font-face {
  font-family: "PT Sans";
  font-style: normal;
  font-weight: 700;
  src: url("..\fonts\ptsans-700.woff2") format("woff2");
  font-display: swap;
}

body {
  font-family: "PT Sans", sans-serif;
  font-size: 22px;
  line-height: 26px;
  color: #333333;
  background: #FFFFFF;
}
```

2023-02-11 06:20 UTC, valery163 commented on catalog.html
> +            </a>
Ссылки добавлены для всех гостиниц

2023-02-11 06:22 UTC, valery163 commented on catalog.html
> +        </article>
Вложенность исправлена

2023-02-11 06:22 UTC, valery163 commented on catalog.html
> +        </article>
+1

2023-02-11 06:23 UTC, valery163 commented on catalog.html
> +            </a>
Ссылки добавлены для всех карточек

2023-02-11 06:26 UTC, valery163 commented on index.html
> -        <form class="subscribe-form" action="https://echo.htmlacademy.ru/" method="post">
<form> добавлен

2023-02-11 06:38 UTC, valery163 commented on index.html
> +            </svg>
Отступы добавляются же через CSS в следующей домашке с помощью padding? Или я что-то потаю?

2023-02-11 06:39 UTC, valery163 commented on index.html
> +            </svg>
Тоже не поняла, почему на этом этапе нужно добавлять отступы?

2023-02-11 06:45 UTC, valery163 commented on styles/styles.css
> +  }
Лишние свойства убрала, но размер остался прежним

2023-02-12 18:12 UTC, pavel-nyukalo requested changes

2023-02-12 18:12 UTC, pavel-niukalo commented on catalog.html
> +            </a>
Поскольку сейчас Подробнее и Избранное - отдельные ссылки (это правильно), из этой ссылки их нужно удалить

Должна получиться вот такая карточка

```html
<li class="product-card"
  <article class="product-card">
    <a class="product-card-link" href="product.html">
      <img class="product-card-image" src="images/catalog-main-images/card-villas-at-poco.jpg" width="300" height="212" alt="Госница Villas at Poco Diablo.">
      <h3 class="product-card-title">Villas at Poco Diablo</h3>
    </a>
    <a href="#" class="product-card-detail">Подробнее</a>
    <a href="#" class="product-card-favorites">Избранное</a>
    <p class="product-card-type">Гостиница</p>
    <b class="product-card-price">От 5000 ₽</b>
    <p class="product-card-rating">Рейтинг</p>
  </article>
</li>
```

2023-02-12 18:12 UTC, pavel-niukalo commented on catalog.html
> +              <p class="product-card-favorites">Избранное</p>
Соответственно, их нужно удалить из всех карточек

2023-02-12 18:12 UTC, pavel-niukalo commented on index.html
> +            </a>
Вот тут не поправлено. В каталоге нужно сделать аналогичную разметку

![image](https://user-images.githubusercontent.com/52506235/218327865-5edf5bd7-4159-43f3-8b6a-f7717df425a3.png)

2023-02-12 18:12 UTC, pavel-niukalo commented on index.html
> +            </a>
Так же. Делаем аналогичную разметку в каталоге и убираем точку у `12.` -> `12`

2023-02-12 18:12 UTC, pavel-niukalo commented on index.html
> +          <li class="advantages-item-bridge">
Насчет этих названий (`advantages-item-town`, `advantages-item-road`, `advantages-item-bridge`)

В целом, карточки у нас выглядят плюс-минус одинаково, одинаковые шрифты, одинаковые отступы. Есть отличия да, например то что с картинками у нас большой блок, потом фоновый цвет чуть разный. Но в целом они одинаковые. Поэтому им я бы оставил один класс общий, а если что-то и меняется, то делал бы это доп. классами.

Поясню почему.

Представь, что у нас тут будет 10 блоков и все они +- одинаковые.
Если мы даем им один общий класс, то в него мы можем положить общие стили

```css
.advantages-item {
  // предположим, чисто гипотетически
  padding: 20px;
  font-size: 21px;
  line-height: 30px;
  и тд.
}
```

А вот если делать их разными классами, то это может вылиться вот в такое

```css
.advantages-item-town,
.advantages-item-road,
.advantages-item-bridge,
.advantages-item-...,
.advantages-item-...,
.advantages-item-...,
.advantages-item-...,
.advantages-item-... { <-- и так сколько у нас будет пунктов
  // предположим, чисто гипотетически
  padding: 20px;
  font-size: 21px;
  line-height: 30px;
  и тд.
}
```

Или еще хуже

```css
.advantages-item-town {
  // предположим, чисто гипотетически
  padding: 20px;
  font-size: 21px;
  line-height: 30px;
  и тд.
}

.advantages-item-road {
  // предположим, чисто гипотетически
  padding: 20px;
  font-size: 21px;
  line-height: 30px;
  и тд.
}

.advantages-item-bridge {
  // предположим, чисто гипотетически
  padding: 20px;
  font-size: 21px;
  line-height: 30px;
  и тд.
}

.advantages-item-... {
  // предположим, чисто гипотетически
  padding: 20px;
  font-size: 21px;
  line-height: 30px;
  и тд.
}

.advantages-item-... {
  // предположим, чисто гипотетически
  padding: 20px;
  font-size: 21px;
  line-height: 30px;
  и тд.
}

.advantages-item-... {
  // предположим, чисто гипотетически
  padding: 20px;
  font-size: 21px;
  line-height: 30px;
  и тд.
}

....
```

Поэтому, я бы все же им оставил одинаковые классы, а уже то что отличает одну карточку от другой - делать доп. класс

Например
```html
<li class="advantages-item advantages-item-road">
```

В кол-ве классов на элементе мы не ограничены

2023-02-12 18:12 UTC, pavel-niukalo commented on index.html
> -      </section>
Так, вот эту секцию нам нужно оставить в разметке (исключение - картинки, их убираем из разметки и будем делать через фон)

2023-02-12 18:12 UTC, pavel-nyukalo commented on index.html
> +            <button class="button-subscribe" type="submit">Подписаться</button>
Отформатируй пожалуйста документ, немного отступы у вложенных тегов поехали

2023-02-12 18:12 UTC, pavel-nyukalo commented on index.html
> +            </svg> <! -- Отступы добавляются же через CSS в следующей домашке с помощью padding? Или я что-то потаю? -->
Под отступами я имел ввиду отступы у вложенных тегов. То есть тут должно быть так
```html
<svg ...>
  <path...>
</svg>
```
Сейчас так
```html
<svg ...>
<path...>
</svg>
```

А так да, конечно, отступы уже на сайте (в сетке сайта) будем делать потом. Тут чисто по форматированию

2023-02-12 18:12 UTC, pavel-nyukalo commented on index.html
> +            </svg>
Тут аналогичная ситуация - про отступы в разметке

2023-02-12 18:12 UTC, pavel-nyukalo commented on index.html
> +            <path fill="#83B3D3" d="M18.94.36H3.51C1.65.36.33 1.95.33 3.76v10.09c0 1.91 1.32 3.5 3.18 3.5h15.65c1.64 0 3.17-1.59 3.17-3.4V3.76c-.22-1.8-1.53-3.4-3.39-3.4ZM7.99 12.89V4.82l7.34 4.04-7.
И так же не забудь сделать так же в каталоге

![image](https://user-images.githubusercontent.com/52506235/218328555-92def22e-445a-4349-a6db-7c49a85c483b.png)

2023-02-12 18:12 UTC, pavel-nyukalo commented on styles/styles.css
> +  src: url("..\fonts\ptsans-700.woff2") format("woff2"); /*Заменила направление слэша, но почему-то символы f и p стали желтыми. Так должно быть?*/
Возможно автоформатировщик подставляет их, но направление слеша не изменено 

![image](https://user-images.githubusercontent.com/52506235/218328604-c9468130-6533-40a3-9767-1b85cad6a57c.png)

Должно быть `../fonts/pt-sans-700.woff2`

2023-02-12 18:12 UTC, pavel-nyukalo commented on styles/styles.css
> +   }
Лишние отступы 

![image](https://user-images.githubusercontent.com/52506235/218328644-eeee918a-bb69-4ceb-8032-4e53f2a7364a.png)

2023-02-12 18:12 UTC, pavel-nyukalo commented on catalog.html
> +        <ul class="navigation-link">
Осторожно меняй класс. Сейчас у тебя один класс на совсем разных элементах - на списке и на ссылках. Легко будет запутаться при стилизации

![image](https://user-images.githubusercontent.com/52506235/218328730-91232624-2f20-4580-b959-3139aef833be.png)

2023-02-12 18:12 UTC, pavel-nyukalo commented on styles/styles.css
> +  }
Здесь так же лишние отступы

![image](https://user-images.githubusercontent.com/52506235/218328755-87fa5a77-ea54-4b2e-a76b-03c136b63470.png)

Должно быть вот как здесь например

![image](https://user-images.githubusercontent.com/52506235/218328767-bd681f43-0a74-422a-99e2-a125ee9c58c8.png)

2023-02-12 18:12 UTC, pavel-nyukalo commented on styles/styles.css
> +  background-image: url(/images/index-main-images/index-background.jpg);
1. Давай писать единообразно и во всех `url` ставить кавычки - `url("....")`
2. Нужно добавить еще `../` в начале. Это означает для системы "поднимись на уровень выше по иерархии" - `url("../images/index-main-images/index-background.jpg")`

Наш файл стилей лежит в папке `styles/`. Соответственно, ему чтобы добраться до папки с картинками нужно "выйти" из своей папки. Это как раз `../`

2023-02-12 18:12 UTC, pavel-nyukalo commented on styles/styles.css
> +.advantages-list {
1. Поправить отступ у `}` (там сейчас 2 пробела, должно быть 0)
2. Так же для единообразия между селекторами должна быть максимум одна пустая строка (сейчас их две - 80 и 81)

2023-02-12 18:12 UTC, pavel-nyukalo commented on styles/styles.css
> +.advantages-item {
И так же для единообразия нужно добавить одну пустую строку

2023-02-12 18:12 UTC, pavel-nyukalo commented on styles/styles.css
> +  }
Отступ у `}` нужно поправить

2023-02-12 18:12 UTC, pavel-nyukalo commented on styles/styles.css
> +  /*Не смогла добавить блоки жилье, еда, сувениры, т.к. из idex.html они были удалены на этапе предыдущей домашки. Я что-то не правильно полняла?*/
Как уже написал - да, в разметку их нужно вернуть, но картинки для них не вставлять, они будут потом фоном

2023-02-12 18:12 UTC, pavel-nyukalo commented on styles/styles.css
> +  }
+1 про отступы

2023-02-12 18:12 UTC, pavel-nyukalo commented on styles/styles.css
> +    }
1. Здесь так же про отступы
2. Тут видимо точка забыта - `.button .interest-button-search`

![image](https://user-images.githubusercontent.com/52506235/218329060-ad8e55d3-74a9-40a5-8bd5-ee6a68daf0fa.png)

(кстати этот селектор означает возьми `.interest-button-search`, который лежит (вложенный) в `.button` - тут все верно, так и задумано?)

3. По поводу картинки так же как выше - нужно добавить `../`

2023-02-20 18:39 UTC, pavel-nyukalo approved these changes

2023-02-20 18:39 UTC, merged