Создает флексы
htmlacademy-htmlcss/2249653-sedona-36 pull request #4
Opened 2023-02-24 08:05 UTC by valery163

2023-02-26 11:49 UTC, pavel-nyukalo requested changes

2023-02-26 11:49 UTC, pavel-nyukalo commented on styles/styles.css
> +  overflow: hidden;
Из-за того, что удалились свойства для контейнера сайт развалился

![image](https://user-images.githubusercontent.com/52506235/221407327-27ab70a0-3aa9-41df-98bb-18c7c44d94b3.png)

Нужны и свойства для `container`, и для `visually-hidden`

```css
.visually-hidden {
  position: absolute;
  width: 1px;
  height: 1px;
  margin: -1px;
  padding: 0;
  border: 0;
  clip: rect(0 0 0 0);
  overflow: hidden;
}

.container {
  margin: auto;
  width: 1200px;
}
```

И тогда уже лучше

![image](https://user-images.githubusercontent.com/52506235/221407422-40190f67-d963-4e6a-8bbd-b738a0e19591.png)

2023-02-26 11:49 UTC, pavel-nyukalo commented on styles/styles.css
> +.navigation-list navigation-user {
Пропущена точка для селектора - `.navigation-list .navigation-user`

![image](https://user-images.githubusercontent.com/52506235/221407492-3f511c07-4983-4b8a-9a81-e351250987f4.png)

Без точки это стилизация по тегу. То есть тут если смотреть селектор, то получается мы ищем тег `<navigation-user>` в классе `.navigation-list`

2023-02-26 11:49 UTC, pavel-nyukalo commented on styles/styles.css
> +
![image](https://user-images.githubusercontent.com/52506235/221407567-772b51ea-1307-4f21-a0eb-720862e68a8a.png)

Эти свойства тоже нам нужны

2023-02-26 11:49 UTC, pavel-nyukalo commented on styles/styles.css
> +  padding: 51px 371px 82px 371px;
Насчет `.main-index` и `.hero`
1. Фоновую картинку я бы задал блоку `hero`, чтобы можно было если что его переставить (вдруг потребовалось бы) и чтобы он был более независим
2. Лучше задавать не жесткую ширину, а минимальную для того чтобы проходило переполнение - `min-height`
3. Так же нужно быть аккуратным с расчетом ширины/высоты. Сейчас у нас есть высота в 485px, и паддинги сверху снизу. Все они идут в расчет высоты и таким образом высота не 485px как по макету, а 618px. Чтобы задать конкретную высоту и чтобы паддинги были внутри так сказать, нужно поставить `box-sizing: border-box`. Я делал [наглядное сравнение](https://codesandbox.io/s/box-sizing-4sdv7), погляди

2023-02-26 11:49 UTC, pavel-nyukalo commented on styles/styles.css
> +  height: 385px;
Насчет списка преимуществ
1. `advantages-list` нужно сделать флекс-контейнером, чтобы элементы можно было бы переносить на новую строку (`flex-wrap: wrap`)
2. `max-width: 400px` нужно задавать тем пунктам, которые не имеют картинки. Ибо картинки у нас лежат внутри `li`, и вот этим двум `li` с картинками нужна ширина 1200px
3. Так же про жестко заданную высоту - нужно сделать `min-height`
4. `display: flex` для `advantages-item` в целом не нужен, только опять же, тем у которых есть картинки
5. И вот тем, у которых есть картинки, заголовок и текст стоит обернуть в `div`, чтобы было проще выстроить

Если что на консультации это разберем

2023-02-26 11:49 UTC, pavel-nyukalo commented on styles/styles.css
> +
Тут нужно оставить только одну строку пустую

2023-02-26 11:49 UTC, pavel-nyukalo commented on styles/styles.css
> +.button button-light {
Аналогично про точку в селекторе

2023-03-02 13:29 UTC, valery163 commented on styles/styles.css
> +.navigation-list navigation-user {
добавила точку

2023-03-02 13:29 UTC, valery163 commented on styles/styles.css
> +
Вернула свойства

2023-03-02 13:30 UTC, valery163 commented on styles/styles.css
> +  padding: 51px 371px 82px 371px;
Изменила по пунктам, но все равно квадратики не выстроились в ряд(

2023-03-02 13:31 UTC, valery163 commented on styles/styles.css
> +  padding: 51px 371px 82px 371px;
Внесла изменения по всем пунктам

2023-03-02 13:32 UTC, valery163 commented on styles/styles.css
> +  height: 385px;
С пунктами преимуществ все равно не вышло красиво, размер все равно разный не смотря на то что одинаковое свойство для индивидуальных классов пунктов списка без картинок.

2023-03-02 13:32 UTC, valery163 commented on styles/styles.css
> +
добавила

2023-03-02 13:33 UTC, valery163 commented on styles/styles.css
> +.button button-light {
Точку селектору добавила

2023-03-07 08:45 UTC, pavel-nyukalo requested changes

2023-03-07 08:45 UTC, pavel-niukalo commented on catalog.html
> +            <div class="catalog-form">
Можно строить сетку без этого дива, он получается опять же лишним (то есть все стили для `catalog-form` перенести в `filter-group` и удалить этот див)

В целом у нас в седоне можно обойтись одной глобальной оберткой (которая весь контент оборачивает)

2023-03-07 08:45 UTC, pavel-nyukalo commented on catalog.html
> +          <div class="catalog-products-conteiner">
Вот этот див тоже не нужен. Он никакие стили не содержит, а просто существует. Тут точно скажут при проверке, что лишние элементы

2023-03-07 08:45 UTC, pavel-nyukalo commented on catalog.html
> +              <div class="view-buttons-wrapper">
Вот эти два дива (`select sorting-type` и `view-buttons-wrapper`) тоже лишние, мы можем стилизовать сразу сами нужные элементы (`select` и `ul`)

2023-03-07 08:45 UTC, pavel-nyukalo commented on catalog.html
> +                      <span class="visually-hidden">Показать карточки</span>
Скрытым описаниям нам нужны точки в конце описаний

2023-03-07 08:45 UTC, pavel-nyukalo commented on catalog.html
> +            <div class="product-card-wrapper">
Вот этот тоже лишний. Можем просто добавить паддинг слева и справа для списка и встанет так же как сейчас

2023-03-07 08:45 UTC, pavel-nyukalo commented on catalog.html
>          <div class="pagination-container">
У пагинации тоже можно удалить контейнер

![image](https://user-images.githubusercontent.com/52506235/223364058-a001555b-4763-4e58-a0e7-5d9dfd3fad72.png)

Вот я тут удалил, и все осталось так же как есть

2023-03-07 08:45 UTC, pavel-nyukalo commented on catalog.html
> +          <section class="subscribe">
Насчет этого дива как раз проговорили, что он тоже не нужен. Так же не забудь добавить доп. класс только в каталоге, поскольку по макету в подписке в каталоге нет фоновой картинки. Вот как раз этим доп. классом мы будем убирать эту картинку

2023-03-07 08:45 UTC, pavel-nyukalo commented on index.html
> +            <div class="phone-footer">
Аналогично, стили `phone-footer` можно применить к `footer-phone` и удалить див

2023-03-07 08:45 UTC, pavel-nyukalo commented on index.html
> +              <a class="htmlacademy-link visually-hidden" href="https://htmlacademy.ru/">.html academy</a>
Вот тут несколько ошибочна реализация. Поскольку ссылка у нас крыта (`visually-hidden`) -> соответственно пользователь не сможет нажать на эту ссылку

Плюс, мы не сможем красить картинку, вставленную через `img` так как нам надо

Поэтому тут нужно
1. Удалить `img`
2. Убрать `visually-hidden` с ссылки
3. Вставить через `svg` картинку внутрь ссылки

Получится что-то типа такого

```html
<section class="footer-website">
  <h2 class="visually-hidden">Сайт исполнителя</h2>
  <a class="htmlacademy-link" href="https://htmlacademy.ru/">
    <span class="visually-hidden">.html academy</span>
    <svg>....</svg>
  </a>
</section>
```

2023-03-07 08:45 UTC, pavel-niukalo commented on styles/styles.css
> +  background-image: url(../images/footer-images/form-index.jpg);
Кавычки в `url` нужны

2023-03-07 08:45 UTC, pavel-niukalo commented on styles/styles.css
> +}
Невалидные значения

![image](https://user-images.githubusercontent.com/52506235/223369891-aaf19319-167a-47b9-bf68-87874b393316.png)

Чтобы задать паддинги сокращенным свойством, нужно их без `;` записывать
`padding: 50px 70px 40px 70px`

2023-03-07 09:06 UTC, valery163 commented on catalog.html
> +            <div class="catalog-form">
Не нужный div удалила

2023-03-07 09:08 UTC, valery163 commented on catalog.html
> +          <div class="catalog-products-conteiner">
Тоже удалила, у него и не было стилей

2023-03-07 09:46 UTC, valery163 commented on catalog.html
> +              <div class="view-buttons-wrapper">
Лишние дивы удалила

2023-03-07 09:47 UTC, valery163 commented on catalog.html
> +                      <span class="visually-hidden">Показать карточки</span>
Добавила точки

2023-03-07 10:29 UTC, valery163 commented on catalog.html
> +            <div class="product-card-wrapper">
Лишнее удалила, паддинги добавила

2023-03-07 10:48 UTC, valery163 commented on catalog.html
> +          <section class="subscribe">
Доп. класс добавила, див удалила

2023-03-07 10:51 UTC, valery163 commented on index.html
> +            <div class="phone-footer">
лишний див удалила, стили перенесла

2023-03-07 12:48 UTC, valery163 commented on index.html
> +              <a class="htmlacademy-link visually-hidden" href="https://htmlacademy.ru/">.html academy</a>
Задала вопрос в личной переписке

2023-03-07 13:19 UTC, valery163 commented on styles/styles.css
> +  background-image: url(../images/footer-images/form-index.jpg);
Кавычки добавила

2023-03-07 13:20 UTC, valery163 commented on styles/styles.css
> +}
Часть паддингов оказалась не нужна, исправила.

2023-03-13 10:19 UTC, pavel-niukalo requested changes
В телеграмме описал моменты, которые надо поправить

2023-03-15 07:54 UTC, pavel-niukalo approved these changes

2023-03-15 07:54 UTC, merged